# Generated by Django 4.2.2 on 2024-04-20 08:59

import core.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.CharField(default=core.utils.generate_model_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('user_log_id', models.CharField(editable=False, max_length=32, null=True)),
                ('valid', models.BooleanField(default=True)),
                ('view_name', models.CharField(editable=False, max_length=128, null=True)),
                ('http_request_type', models.CharField(editable=False, max_length=16, null=True)),
                ('ip_address', models.CharField(editable=False, max_length=64, null=True)),
                ('path', models.CharField(editable=False, max_length=1000, null=True)),
                ('full_path', models.CharField(editable=False, max_length=1000, null=True)),
                ('data', models.JSONField(null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user_log_id'], name='user_log_index')],
            },
        ),
    ]
