# Generated by Django 4.2.2 on 2024-04-20 22:03

import core.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationPing',
            fields=[
                ('id', models.CharField(default=core.utils.generate_model_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('location_ping_id', models.CharField(editable=False, max_length=32, null=True)),
                ('lat', models.FloatField(default=True)),
                ('lng', models.FloatField(default=True)),
                ('geocoordinate', models.CharField(editable=False, max_length=128, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('accuracy', models.FloatField(default=True)),
                ('altitude', models.FloatField(default=True)),
                ('speed', models.FloatField(default=True)),
                ('heading', models.FloatField(default=True)),
                ('data', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['location_ping_id'], name='location_ping_index')],
            },
        ),
    ]
