# Generated by Django 4.2.2 on 2024-04-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_locationping'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationping',
            name='status',
            field=models.CharField(default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='locationping',
            name='geocoordinate',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
