# Generated by Django 4.2.2 on 2024-04-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_locationping_status_alter_locationping_geocoordinate'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationping',
            name='config',
            field=models.JSONField(null=True),
        ),
    ]
